[workspace]
members = ["raylib", "term"]
# members = ["term"]

[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rayon = "1.10.0"
smolmatrix = "0.1.3"

[features]
report_progress = []
